// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmUBSSwbm01JXgui5T1evKCVpUNziGOy0',
    appId: '1:244223044032:web:744baaf35602e352f94025',
    messagingSenderId: '244223044032',
    projectId: 'readers-5ed5d',
    authDomain: 'readers-5ed5d.firebaseapp.com',
    storageBucket: 'readers-5ed5d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC55pe6KQHZAr_mcRX9oUZNzIk-WomzGZg',
    appId: '1:244223044032:android:2e384db21def375ff94025',
    messagingSenderId: '244223044032',
    projectId: 'readers-5ed5d',
    storageBucket: 'readers-5ed5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFd1k6qoN_LMfsy4VIyc5Ifv1IYyNe84U',
    appId: '1:244223044032:ios:69c145f9a43c9154f94025',
    messagingSenderId: '244223044032',
    projectId: 'readers-5ed5d',
    storageBucket: 'readers-5ed5d.appspot.com',
    iosClientId: '244223044032-5cd6qn9j6s7hqqh3g1nosr0d9qr06fek.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFd1k6qoN_LMfsy4VIyc5Ifv1IYyNe84U',
    appId: '1:244223044032:ios:eda806f333717428f94025',
    messagingSenderId: '244223044032',
    projectId: 'readers-5ed5d',
    storageBucket: 'readers-5ed5d.appspot.com',
    iosClientId: '244223044032-n10j27000savupkvdqpjcscg6du45ucj.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookshop.RunnerTests',
  );
}
